-- DROP DATABASE MHS ;
CREATE DATABASE IF NOT EXISTS MHS;
USE MHS;

-- DROP TABLE INVOICE;
-- DROP TABLE INVOICE_DETAIL;
-- DROP TABLE MAKES_APPOINTMENT;
-- DROP TABLE TREATS;
-- DROP TABLE PATIENT;
-- DROP TABLE INSURANCE_COMPANY;
-- DROP TABLE OUTPATIENT_SURGERY;
-- DROP TABLE OFFICE;
-- DROP TABLE DOCTOR;
-- DROP TABLE ADMIN;
-- DROP TABLE NURSE;
-- DROP TABLE OTHER_HCP;
-- DROP TABLE EMPLOYEE;
-- DROP TABLE FACILITY;

CREATE TABLE FACILITY (
    FacID INT PRIMARY KEY,
    Street VARCHAR(255) NOT NULL,
    City VARCHAR(100) NOT NULL,
    State VARCHAR(100) NOT NULL,
    Zip VARCHAR(10) NOT NULL,
    Size INT NOT NULL,
    Ftype ENUM('Office','OPS') NOT NULL
);

CREATE TABLE EMPLOYEE (
    EmpID INT PRIMARY KEY,
    SSN VARCHAR(9) UNIQUE NOT NULL,
    E_FacID INT NOT NULL,
    Street VARCHAR(255) NOT NULL,
    City VARCHAR(100) NOT NULL,
    State VARCHAR(100) NOT NULL,
    Zip VARCHAR(10) NOT NULL,
    FName VARCHAR(100) NOT NULL,
    LName VARCHAR(100) NOT NULL,
    Minit CHAR(1) ,
    Salary DECIMAL(10, 2) NOT NULL, 
    Hiredate DATE NOT NULL,
    Jobclass ENUM('MD', 'Nurse', 'Admin', 'HCP') NOT NULL,
    FOREIGN KEY (E_FacID) REFERENCES Facility(FacID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE  OTHER_HCP (
    HCP_EmpID INT PRIMARY KEY,
    Job_Title VARCHAR(100) NOT NULL,
    FOREIGN KEY (HCP_EmpID) REFERENCES Employee(EmpID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE  NURSE (
    N_EmpID INT PRIMARY KEY,
    Certification VARCHAR(100) NOT NULL,
    FOREIGN KEY (N_EmpID) REFERENCES Employee(EmpID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE ADMIN (
    A_EmpID INT PRIMARY KEY,
    Job_Title VARCHAR(100) NOT NULL,
    FOREIGN KEY (A_EmpID) REFERENCES Employee(EmpID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE DOCTOR (
    D_EmpID INT PRIMARY KEY,
    BC_Date DATE,
    Speciality VARCHAR(100) NOT NULL,
    FOREIGN KEY (D_EmpID) REFERENCES Employee(EmpID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE OFFICE (
    O_FacID INT PRIMARY KEY ,
    Office_count INT,
    FOREIGN KEY (O_FacID) REFERENCES Facility(FacID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE OUTPATIENT_SURGERY (
    OP_FacID INT PRIMARY KEY ,
    Room_count INT NOT NULL,
    P_code VARCHAR(100) NOT NULL,
    Des VARCHAR(100),
    FOREIGN KEY (OP_FacID) REFERENCES Facility(FacID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE  INSURANCE_COMPANY (
    Ins_ID INT PRIMARY KEY ,
    IName VARCHAR(100) NOT NULL,
    Street VARCHAR(255) NOT NULL,
    City VARCHAR(100) NOT NULL,
    State VARCHAR(100) NOT NULL,
    Zip VARCHAR(10) NOT NULL
); 

CREATE TABLE  PATIENT (
    P_id INT PRIMARY KEY ,
    FName VARCHAR(100)NOT NULL,
    LName VARCHAR(100) NOT NULL,
    Minit CHAR(1),
    Street VARCHAR(255),
    City VARCHAR(100),
    State VARCHAR(100),
    Zip VARCHAR(10),
    Primary_D_EmpID INT,
    P_Ins_id INT,
    FOREIGN KEY (Primary_D_EmpID) REFERENCES Doctor(D_EmpID) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (P_Ins_id) REFERENCES Insurance_Company(Ins_ID) ON DELETE CASCADE ON UPDATE CASCADE
); 

CREATE TABLE  TREATS (
    D_EmpID INT ,
    P_ID INT ,
    PRIMARY KEY(D_EmpID, P_ID),
    FOREIGN KEY (D_EmpID) REFERENCES Doctor(D_EmpID) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (P_ID) REFERENCES Patient(P_id) ON DELETE CASCADE ON UPDATE CASCADE
    
); 

CREATE TABLE  	MAKES_APPOINTMENT (
	App_D_EID INT ,
    App_P_ID INT ,
    App_F_ID INT ,
    Date_Time DATETIME ,
    PRIMARY KEY (App_D_EID, App_P_ID, App_F_ID, Date_Time),
    FOREIGN KEY (App_D_EID) REFERENCES Doctor(D_EmpID) ON DELETE CASCADE ON UPDATE CASCADE, 
    FOREIGN KEY (App_P_ID) REFERENCES Patient(P_id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (App_F_ID) REFERENCES Facility(FacID) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE INDEX idx_Date_Time ON MAKES_APPOINTMENT(Date_Time);
CREATE TABLE  	INVOICE_DETAIL (
    Inv_id INT ,
    Doc_App_ID INT ,
    Pat_App_ID INT ,
    Fac_App_ID INT ,
    App_Date_Time DateTime,
    Cost DECIMAL(10, 2) NOT NULL,
    PRIMARY KEY (Inv_id, Doc_App_ID, Pat_App_ID, Fac_App_ID,App_Date_Time),
    FOREIGN KEY (Doc_App_ID) REFERENCES Makes_Appointment(App_D_EID) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (Pat_App_ID) REFERENCES Makes_Appointment(App_P_ID) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (Fac_App_ID) REFERENCES Makes_Appointment(App_F_ID) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (App_Date_Time) REFERENCES Makes_Appointment(Date_Time) ON DELETE CASCADE ON UPDATE CASCADE
    
);

CREATE TABLE  	INVOICE (
    Inv_id INT PRIMARY KEY ,
    Inv_Ins_id INT NOT NULL,
    Inv_date DATE NOT NULL,
    Inv_amt DECIMAL(10, 2) NOT NULL,
    FOREIGN KEY (Inv_Ins_id) REFERENCES Insurance_Company(Ins_ID) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (Inv_id) REFERENCES Invoice_detail(Inv_id) ON DELETE CASCADE ON UPDATE CASCADE
);